use_frameworks!

platform :ios, '13.0'

target 'HFUtils_Example' do
  pod 'HFUtils', :path => '../'
  
  pod 'HFMoMain', '0.1.0'

  target 'HFUtils_Tests' do
    inherit! :search_paths

    
  end
end
